
import React from 'react';

export default function TermsOfService() {
    return (
        <div>
            <h1>TERMS OF SERVICE</h1>
            <p>Last Updated: January 1, 2026</p>

            <h2>1. ACCEPTANCE OF TERMS</h2>
            <p>These Terms of Service ("Terms") constitute a legally binding agreement between you and Novelty Concepts Ltd ("Company," "we," "us," or "our") governing your use of the Novelty Concepts Ltd HRM & Payroll System (the "System" or "Service").</p>
            <p>By accessing or using the System, you agree to be bound by these Terms. If you do not agree, do not use the System.</p>

            <h2>2. DEFINITIONS</h2>
            <ul>
                <li><strong>"Client" or "Organization":</strong> The company or entity subscribing to the Service</li>
                <li><strong>"User":</strong> Any individual accessing the System (administrators, HR managers, employees, etc.)</li>
                <li><strong>"Account":</strong> The Organization's subscription account</li>
                <li><strong>"Data":</strong> All information entered into, processed by, or generated by the System</li>
                <li><strong>"Authorized User":</strong> An individual granted access by the Organization</li>
            </ul>

            <h2>3. SERVICE DESCRIPTION</h2>
            <p>The Novelty Concepts Ltd HRM & Payroll System is a cloud-based Software-as-a-Service (SaaS) platform providing:</p>
            <ul>
                <li>Recruitment and Applicant Tracking</li>
                <li>Employee Information Management</li>
                <li>Leave and Attendance Tracking</li>
                <li>Payroll Processing</li>
                <li>Performance Management</li>
                <li>Training and Development Tools</li>
                <li>Reporting and Analytics</li>
            </ul>
            <p>Features and functionality may be updated or modified at our discretion.</p>

            <h2>4. ACCOUNT REGISTRATION AND ELIGIBILITY</h2>
            <h3>4.1 Eligibility</h3>
            <p>To use the System, you must:</p>
            <ul>
                <li>Be a legally registered business entity in Ghana or authorized to do business in Ghana</li>
                <li>Be at least 18 years of age</li>
                <li>Provide accurate and complete registration information</li>
                <li>Have the legal authority to bind your Organization to these Terms</li>
            </ul>

            <h3>4.2 Account Creation</h3>
            <ul>
                <li>One Organization representative (Administrator) must register the Account</li>
                <li>Registration requires: company name, contact details, billing information</li>
                <li>You are responsible for maintaining the security of your Account credentials</li>
            </ul>

            <h3>4.3 Account Security</h3>
            <p>You agree to:</p>
            <ul>
                <li>Use strong passwords and change them regularly</li>
                <li>Not share login credentials</li>
                <li>Notify us immediately of unauthorized access</li>
                <li>Be responsible for all activity under your Account</li>
            </ul>
            <p>We are not liable for losses due to compromised credentials.</p>

            <h2>5. USER ACCOUNTS AND ACCESS</h2>
            <h3>5.1 User Provisioning</h3>
            <ul>
                <li>Organizations control user access within their Account</li>
                <li>Users are assigned roles with specific permissions</li>
                <li>Organizations are responsible for managing user access</li>
            </ul>

            <h3>5.2 User Responsibilities</h3>
            <p>Users agree to:</p>
            <ul>
                <li>Provide accurate information</li>
                <li>Use the System only for lawful purposes</li>
                <li>Comply with their Organization's policies</li>
                <li>Respect the privacy of other users</li>
                <li>Not attempt to breach security measures</li>
            </ul>

            <h3>5.3 User Termination</h3>
            <p>Organizations may terminate user access at any time. We may suspend or terminate access for Terms violations.</p>

            <h2>6. FEES AND PAYMENT</h2>
            <h3>6.1 Subscription Fees</h3>
            <ul>
                <li>Fees are based on the selected subscription plan and number of active employees</li>
                <li>Current pricing is available at [website] or by contacting sales</li>
                <li>Fees are payable in Ghana Cedis (GHS) or US Dollars (USD)</li>
            </ul>

            <h3>6.2 Billing</h3>
            <ul>
                <li>Subscriptions are billed monthly or annually (as selected)</li>
                <li>Payment is due in advance</li>
                <li>Late payments may result in service suspension</li>
                <li>A late fee of 5% per month may apply to overdue amounts</li>
            </ul>

            <h3>6.3 Payment Methods</h3>
            <ul>
                <li>Bank transfer, mobile money, or credit/debit card</li>
                <li>Payment details must be kept current</li>
                <li>Failed payments may result in service interruption</li>
            </ul>

            <h3>6.4 Price Changes</h3>
            <ul>
                <li>We reserve the right to modify pricing with 60 days' notice</li>
                <li>Price changes apply at the next renewal period</li>
                <li>Continued use after price changes constitutes acceptance</li>
            </ul>

            <h3>6.5 Taxes</h3>
            <ul>
                <li>Fees do not include applicable taxes (VAT, withholding tax, etc.)</li>
                <li>You are responsible for all taxes associated with your subscription</li>
            </ul>

            <h3>6.6 Refunds</h3>
            <ul>
                <li>Subscription fees are non-refundable except as required by law</li>
                <li>Overpayments will be credited to your Account or refunded</li>
            </ul>

            <h2>7. DATA OWNERSHIP AND USAGE</h2>
            <h3>7.1 Your Data</h3>
            <ul>
                <li>Organizations retain all rights to data entered into the System</li>
                <li>You grant us a license to process your data to provide the Service</li>
                <li>We do not claim ownership of your data</li>
            </ul>

            <h3>7.2 Our Use of Data</h3>
            <p>We may use aggregated, anonymized data for:</p>
            <ul>
                <li>Service improvement and development</li>
                <li>Industry benchmarking and research</li>
                <li>Marketing and promotional purposes</li>
            </ul>
            <p>We will never sell identifiable customer data.</p>

            <h3>7.3 Data Backup</h3>
            <ul>
                <li>We perform regular automated backups</li>
                <li>Backups are retained for 30 days</li>
                <li>You are responsible for maintaining additional backups if desired</li>
            </ul>

            <h3>7.4 Data Export</h3>
            <ul>
                <li>You may export your data at any time in CSV or Excel format</li>
                <li>Upon termination, you have 30 days to export data before deletion</li>
            </ul>

            <h2>8. INTELLECTUAL PROPERTY</h2>
            <h3>8.1 Our IP Rights</h3>
            <p>The System, including all software, designs, text, graphics, and other content, is owned by Novelty Concepts Ltd and protected by:</p>
            <ul>
                <li>Copyright laws</li>
                <li>Trademark laws</li>
                <li>Trade secret laws</li>
                <li>International treaties</li>
            </ul>
            <p>You may not:</p>
            <ul>
                <li>Copy, modify, or reverse engineer the System</li>
                <li>Remove or alter any proprietary notices</li>
                <li>Use our trademarks without permission</li>
                <li>Create derivative works based on the System</li>
            </ul>

            <h3>8.2 User Feedback</h3>
            <p>If you provide suggestions or feedback about the System, we may use it without compensation or obligation to you.</p>

            <h2>9. SERVICE AVAILABILITY</h2>
            <h3>9.1 Uptime Commitment</h3>
            <p>We strive to maintain 99.5% uptime, excluding:</p>
            <ul>
                <li>Scheduled maintenance (notified in advance)</li>
                <li>Force majeure events</li>
                <li>Issues caused by third-party services</li>
                <li>User error or misuse</li>
            </ul>

            <h3>9.2 Maintenance</h3>
            <ul>
                <li>Scheduled maintenance will be announced 72 hours in advance</li>
                <li>Emergency maintenance may occur without notice</li>
                <li>We will minimize disruption during maintenance windows</li>
            </ul>

            <h3>9.3 No Guarantee</h3>
            <p>The Service is provided "as is" without warranties of uninterrupted or error-free operation.</p>

            <h2>10. SUPPORT</h2>
            <h3>10.1 Support Channels</h3>
            <ul>
                <li>Email: support@thenoveltyconcepts.com</li>
                <li>Phone: +233 20 021 7444 (Business hours: 8 AM - 5 PM GMT, Monday-Friday)</li>
                <li>In-app support ticket system</li>
            </ul>

            <h3>10.2 Support Response Times</h3>
            <ul>
                <li>Critical issues: 4 business hours</li>
                <li>High priority: 8 business hours</li>
                <li>Normal priority: 24 business hours</li>
                <li>Low priority: 48 business hours</li>
            </ul>

            <h3>10.3 Scope of Support</h3>
            <p>Support includes:</p>
            <ul>
                <li>Technical issues and bug resolution</li>
                <li>Feature guidance and training</li>
                <li>Account configuration assistance</li>
            </ul>
            <p>Support does not include:</p>
            <ul>
                <li>Custom development</li>
                <li>Data entry services</li>
                <li>On-site support</li>
            </ul>

            <h2>11. ACCEPTABLE USE POLICY</h2>
            <p>You agree NOT to:</p>
            <ul>
                <li>Violate any laws or regulations</li>
                <li>Infringe on intellectual property rights</li>
                <li>Upload malicious software or code</li>
                <li>Attempt unauthorized access to the System</li>
                <li>Interfere with the System's operation</li>
                <li>Use the System to send spam or phishing content</li>
                <li>Impersonate others or misrepresent affiliations</li>
                <li>Harass, abuse, or harm other users</li>
                <li>Scrape or data mine the System</li>
                <li>Resell or sublicense the Service without permission</li>
            </ul>
            <p>Violations may result in immediate account suspension or termination.</p>

            <h2>12. CONFIDENTIALITY</h2>
            <h3>12.1 Confidential Information</h3>
            <p>Each party agrees to protect the other's confidential information, including:</p>
            <ul>
                <li>Business information and strategies</li>
                <li>Technical information and data</li>
                <li>Financial information</li>
                <li>Customer lists</li>
            </ul>

            <h3>12.2 Exceptions</h3>
            <p>Confidentiality obligations do not apply to information that:</p>
            <ul>
                <li>Is publicly available</li>
                <li>Was known prior to disclosure</li>
                <li>Is independently developed</li>
                <li>Must be disclosed by law</li>
            </ul>

            <h3>12.3 Term</h3>
            <p>Confidentiality obligations survive termination of these Terms for 5 years.</p>

            <h2>13. TERM AND TERMINATION</h2>
            <h3>13.1 Term</h3>
            <p>These Terms begin when you accept them and continue until terminated.</p>

            <h3>13.2 Termination by You</h3>
            <p>You may terminate by:</p>
            <ul>
                <li>Providing 30 days' written notice</li>
                <li>Ceasing all use of the System</li>
                <li>Paying any outstanding fees</li>
            </ul>

            <h3>13.3 Termination by Us</h3>
            <p>We may terminate immediately if you:</p>
            <ul>
                <li>Breach these Terms</li>
                <li>Fail to pay fees</li>
                <li>Engage in fraudulent activity</li>
                <li>Violate applicable laws</li>
            </ul>

            <h3>13.4 Effect of Termination</h3>
            <p>Upon termination:</p>
            <ul>
                <li>Your access to the System will cease</li>
                <li>Outstanding fees become immediately due</li>
                <li>You have 30 days to export your data</li>
                <li>After 30 days, your data will be permanently deleted</li>
                <li>Certain provisions (liability, indemnification) survive termination</li>
            </ul>

            <h3>13.5 No Refunds on Termination</h3>
            <p>Fees paid are non-refundable upon termination (except for our breach).</p>

            <h2>14. LIMITATION OF LIABILITY</h2>
            <h3>14.1 Disclaimer of Warranties</h3>
            <p>THE SYSTEM IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO:</p>
            <ul>
                <li>MERCHANTABILITY</li>
                <li>FITNESS FOR A PARTICULAR PURPOSE</li>
                <li>NON-INFRINGEMENT</li>
                <li>ACCURACY OR RELIABILITY</li>
            </ul>

            <h3>14.2 Limitation of Damages</h3>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, NOVCON GHANA SHALL NOT BE LIABLE FOR:</p>
            <ul>
                <li>INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES</li>
                <li>LOSS OF PROFITS, DATA, OR BUSINESS OPPORTUNITIES</li>
                <li>DAMAGES RESULTING FROM SERVICE INTERRUPTIONS</li>
                <li>DAMAGES CAUSED BY THIRD-PARTY SERVICES</li>
            </ul>

            <h3>14.3 Cap on Liability</h3>
            <p>OUR TOTAL LIABILITY TO YOU SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS PRECEDING THE CLAIM.</p>

            <h3>14.4 Exceptions</h3>
            <p>These limitations do not apply to:</p>
            <ul>
                <li>Our gross negligence or willful misconduct</li>
                <li>Violations of applicable law</li>
                <li>Liability that cannot be limited by law</li>
            </ul>

            <h2>15. INDEMNIFICATION</h2>
            <p>You agree to indemnify and hold harmless Novelty Concepts Ltd, its officers, directors, employees, and agents from:</p>
            <ul>
                <li>Claims arising from your use of the System</li>
                <li>Your violation of these Terms</li>
                <li>Your violation of any laws or rights of third parties</li>
                <li>Your data or content</li>
            </ul>
            <p>We will notify you of claims and allow you to defend (at your expense).</p>

            <h2>16. DISPUTE RESOLUTION</h2>
            <h3>16.1 Governing Law</h3>
            <p>These Terms are governed by the laws of Ghana.</p>

            <h3>16.2 Jurisdiction</h3>
            <p>Any disputes shall be resolved in the courts of Accra, Ghana.</p>

            <h3>16.3 Arbitration (Optional)</h3>
            <p>Parties may agree to binding arbitration under the rules of the Ghana Arbitration Centre before resorting to litigation.</p>

            <h3>16.4 Legal Fees</h3>
            <p>The prevailing party in any dispute may recover reasonable legal fees.</p>

            <h2>17. MODIFICATIONS TO TERMS</h2>
            <h3>17.1 Right to Modify</h3>
            <p>We may modify these Terms at any time by:</p>
            <ul>
                <li>Posting updated Terms on the System</li>
                <li>Notifying you via email or in-app notification</li>
            </ul>

            <h3>17.2 Acceptance of Changes</h3>
            <p>Continued use after modifications constitutes acceptance. If you do not agree, you must terminate your Account.</p>

            <h3>17.3 Material Changes</h3>
            <p>For material changes, we will provide 30 days' notice before they take effect.</p>

            <h2>18. GENERAL PROVISIONS</h2>
            <h3>18.1 Entire Agreement</h3>
            <p>These Terms, together with the Privacy Policy and any other referenced policies, constitute the entire agreement between you and Novelty Concepts Ltd.</p>

            <h3>18.2 Severability</h3>
            <p>If any provision is found invalid or unenforceable, the remaining provisions remain in effect.</p>

            <h3>18.3 Waiver</h3>
            <p>Failure to enforce any provision does not waive our right to enforce it later.</p>

            <h3>18.4 Assignment</h3>
            <p>You may not assign these Terms without our written consent. We may assign these Terms to any successor or affiliate.</p>

            <h3>18.5 Force Majeure</h3>
            <p>Neither party is liable for delays or failures due to circumstances beyond reasonable control (natural disasters, war, strikes, government actions, etc.).</p>

            <h3>18.6 Independent Contractors</h3>
            <p>The parties are independent contractors. Nothing creates a partnership, joint venture, or employment relationship.</p>

            <h3>18.7 Notices</h3>
            <p>Notices must be in writing and sent to:</p>
            <ul>
                <li>To Novelty Concepts Ltd: legal@novconghana.com or [physical address]</li>
                <li>To You: The email associated with your Account</li>
            </ul>

            <h3>18.8 Language</h3>
            <p>These Terms are written in English. Translations are for convenience only; the English version controls.</p>

            <h2>19. CONTACT INFORMATION</h2>
            <p>For questions about these Terms:</p>
            <p>Novelty Concepts Ltd 59 Black Hoop Lane, Community 8, Tema Accra, Ghana</p>
            <p>Email: support@thenoveltyconcepts.com: +233 20 021 7444</p>
        </div>
    );
}
